<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0-android</TargetFramework>
        <SupportedOSPlatformVersion>21.0</SupportedOSPlatformVersion>
        <OutputType>Exe</OutputType>
        <RootNamespace>spotifete</RootNamespace>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UseMaui>true</UseMaui>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Maui.Controls" Version="$(MauiVersion)"/>
        <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="9.0.0"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\spotifete\spotifete.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <AndroidResource Update="Resources\mipmap-hdpi\spotifete_icon.png">
            <SubType>Designer</SubType>
        </AndroidResource>
        <AndroidResource Update="Resources\drawable\spotifete_icon.png">
            <SubType>Designer</SubType>
        </AndroidResource>
    </ItemGroup>

</Project>
