// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ChangeFallbackPlaylistRequest
    /// </summary>
    public partial class ChangeFallbackPlaylistRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ChangeFallbackPlaylistRequest" /> class.
        /// </summary>
        /// <param name="loginSessionId">loginSessionId</param>
        /// <param name="newFallbackPlaylistId">newFallbackPlaylistId</param>
        [JsonConstructor]
        public ChangeFallbackPlaylistRequest(Option<string?> loginSessionId = default, Option<string?> newFallbackPlaylistId = default)
        {
            LoginSessionIdOption = loginSessionId;
            NewFallbackPlaylistIdOption = newFallbackPlaylistId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LoginSessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LoginSessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LoginSessionId
        /// </summary>
        [JsonPropertyName("login_session_id")]
        public string? LoginSessionId { get { return this.LoginSessionIdOption; } set { this.LoginSessionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of NewFallbackPlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NewFallbackPlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets NewFallbackPlaylistId
        /// </summary>
        [JsonPropertyName("new_fallback_playlist_id")]
        public string? NewFallbackPlaylistId { get { return this.NewFallbackPlaylistIdOption; } set { this.NewFallbackPlaylistIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ChangeFallbackPlaylistRequest {\n");
            sb.Append("  NewFallbackPlaylistId: ").Append(NewFallbackPlaylistId).Append("\n");
            sb.Append("  LoginSessionId: ").Append(LoginSessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ChangeFallbackPlaylistRequest" />
    /// </summary>
    public class ChangeFallbackPlaylistRequestJsonConverter : JsonConverter<ChangeFallbackPlaylistRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="ChangeFallbackPlaylistRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ChangeFallbackPlaylistRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> loginSessionId = default;
            Option<string?> newFallbackPlaylistId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "login_session_id":
                            loginSessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "new_fallback_playlist_id":
                            newFallbackPlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (loginSessionId.IsSet && loginSessionId.Value == null)
                throw new ArgumentNullException(nameof(loginSessionId), "Property is not nullable for class ChangeFallbackPlaylistRequest.");

            if (newFallbackPlaylistId.IsSet && newFallbackPlaylistId.Value == null)
                throw new ArgumentNullException(nameof(newFallbackPlaylistId), "Property is not nullable for class ChangeFallbackPlaylistRequest.");

            return new ChangeFallbackPlaylistRequest(loginSessionId, newFallbackPlaylistId);
        }

        /// <summary>
        /// Serializes a <see cref="ChangeFallbackPlaylistRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changeFallbackPlaylistRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ChangeFallbackPlaylistRequest changeFallbackPlaylistRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, changeFallbackPlaylistRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ChangeFallbackPlaylistRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="changeFallbackPlaylistRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ChangeFallbackPlaylistRequest changeFallbackPlaylistRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (changeFallbackPlaylistRequest.LoginSessionIdOption.IsSet && changeFallbackPlaylistRequest.LoginSessionId == null)
                throw new ArgumentNullException(nameof(changeFallbackPlaylistRequest.LoginSessionId), "Property is required for class ChangeFallbackPlaylistRequest.");

            if (changeFallbackPlaylistRequest.NewFallbackPlaylistIdOption.IsSet && changeFallbackPlaylistRequest.NewFallbackPlaylistId == null)
                throw new ArgumentNullException(nameof(changeFallbackPlaylistRequest.NewFallbackPlaylistId), "Property is required for class ChangeFallbackPlaylistRequest.");

            if (changeFallbackPlaylistRequest.LoginSessionIdOption.IsSet)
                writer.WriteString("login_session_id", changeFallbackPlaylistRequest.LoginSessionId);

            if (changeFallbackPlaylistRequest.NewFallbackPlaylistIdOption.IsSet)
                writer.WriteString("new_fallback_playlist_id", changeFallbackPlaylistRequest.NewFallbackPlaylistId);
        }
    }
}
