// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// DeleteRequestFromQueueRequest
    /// </summary>
    public partial class DeleteRequestFromQueueRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeleteRequestFromQueueRequest" /> class.
        /// </summary>
        /// <param name="loginSessionId">loginSessionId</param>
        /// <param name="spotifyTrackId">spotifyTrackId</param>
        [JsonConstructor]
        public DeleteRequestFromQueueRequest(Option<string?> loginSessionId = default, Option<string?> spotifyTrackId = default)
        {
            LoginSessionIdOption = loginSessionId;
            SpotifyTrackIdOption = spotifyTrackId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LoginSessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LoginSessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LoginSessionId
        /// </summary>
        [JsonPropertyName("login_session_id")]
        public string? LoginSessionId { get { return this.LoginSessionIdOption; } set { this.LoginSessionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyTrackId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyTrackIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyTrackId
        /// </summary>
        [JsonPropertyName("spotify_track_id")]
        public string? SpotifyTrackId { get { return this.SpotifyTrackIdOption; } set { this.SpotifyTrackIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DeleteRequestFromQueueRequest {\n");
            sb.Append("  SpotifyTrackId: ").Append(SpotifyTrackId).Append("\n");
            sb.Append("  LoginSessionId: ").Append(LoginSessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="DeleteRequestFromQueueRequest" />
    /// </summary>
    public class DeleteRequestFromQueueRequestJsonConverter : JsonConverter<DeleteRequestFromQueueRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="DeleteRequestFromQueueRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override DeleteRequestFromQueueRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> loginSessionId = default;
            Option<string?> spotifyTrackId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "login_session_id":
                            loginSessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "spotify_track_id":
                            spotifyTrackId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (loginSessionId.IsSet && loginSessionId.Value == null)
                throw new ArgumentNullException(nameof(loginSessionId), "Property is not nullable for class DeleteRequestFromQueueRequest.");

            if (spotifyTrackId.IsSet && spotifyTrackId.Value == null)
                throw new ArgumentNullException(nameof(spotifyTrackId), "Property is not nullable for class DeleteRequestFromQueueRequest.");

            return new DeleteRequestFromQueueRequest(loginSessionId, spotifyTrackId);
        }

        /// <summary>
        /// Serializes a <see cref="DeleteRequestFromQueueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deleteRequestFromQueueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, DeleteRequestFromQueueRequest deleteRequestFromQueueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, deleteRequestFromQueueRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="DeleteRequestFromQueueRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="deleteRequestFromQueueRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, DeleteRequestFromQueueRequest deleteRequestFromQueueRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (deleteRequestFromQueueRequest.LoginSessionIdOption.IsSet && deleteRequestFromQueueRequest.LoginSessionId == null)
                throw new ArgumentNullException(nameof(deleteRequestFromQueueRequest.LoginSessionId), "Property is required for class DeleteRequestFromQueueRequest.");

            if (deleteRequestFromQueueRequest.SpotifyTrackIdOption.IsSet && deleteRequestFromQueueRequest.SpotifyTrackId == null)
                throw new ArgumentNullException(nameof(deleteRequestFromQueueRequest.SpotifyTrackId), "Property is required for class DeleteRequestFromQueueRequest.");

            if (deleteRequestFromQueueRequest.LoginSessionIdOption.IsSet)
                writer.WriteString("login_session_id", deleteRequestFromQueueRequest.LoginSessionId);

            if (deleteRequestFromQueueRequest.SpotifyTrackIdOption.IsSet)
                writer.WriteString("spotify_track_id", deleteRequestFromQueueRequest.SpotifyTrackId);
        }
    }
}
