// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FullListeningSession
    /// </summary>
    public partial class FullListeningSession : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FullListeningSession" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="active">active</param>
        /// <param name="ownerId">ownerId</param>
        /// <param name="joinId">joinId</param>
        /// <param name="queuePlaylistId">queuePlaylistId</param>
        /// <param name="title">title</param>
        /// <param name="fallbackPlaylistId">fallbackPlaylistId</param>
        /// <param name="fallbackPlaylistShuffle">fallbackPlaylistShuffle</param>
        /// <param name="owner">owner</param>
        /// <param name="fallbackPlaylistMetadata">fallbackPlaylistMetadata</param>
        [JsonConstructor]
        public FullListeningSession(Option<long?> id = default, Option<bool?> active = default, Option<long?> ownerId = default, Option<string?> joinId = default, Option<string?> queuePlaylistId = default, Option<string?> title = default, Option<string?> fallbackPlaylistId = default, Option<bool?> fallbackPlaylistShuffle = default, Option<SimpleUser?> owner = default, Option<PlaylistMetadata?> fallbackPlaylistMetadata = default)
        {
            IdOption = id;
            ActiveOption = active;
            OwnerIdOption = ownerId;
            JoinIdOption = joinId;
            QueuePlaylistIdOption = queuePlaylistId;
            TitleOption = title;
            FallbackPlaylistIdOption = fallbackPlaylistId;
            FallbackPlaylistShuffleOption = fallbackPlaylistShuffle;
            OwnerOption = owner;
            FallbackPlaylistMetadataOption = fallbackPlaylistMetadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } set { this.ActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwnerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> OwnerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [JsonPropertyName("owner_id")]
        public long? OwnerId { get { return this.OwnerIdOption; } set { this.OwnerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of JoinId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JoinIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets JoinId
        /// </summary>
        [JsonPropertyName("join_id")]
        public string? JoinId { get { return this.JoinIdOption; } set { this.JoinIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueuePlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueuePlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueuePlaylistId
        /// </summary>
        [JsonPropertyName("queue_playlist_id")]
        public string? QueuePlaylistId { get { return this.QueuePlaylistIdOption; } set { this.QueuePlaylistIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackPlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FallbackPlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackPlaylistId
        /// </summary>
        [JsonPropertyName("fallback_playlist_id")]
        public string? FallbackPlaylistId { get { return this.FallbackPlaylistIdOption; } set { this.FallbackPlaylistIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackPlaylistShuffle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FallbackPlaylistShuffleOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackPlaylistShuffle
        /// </summary>
        [JsonPropertyName("fallback_playlist_shuffle")]
        public bool? FallbackPlaylistShuffle { get { return this.FallbackPlaylistShuffleOption; } set { this.FallbackPlaylistShuffleOption = new(value); } }

        /// <summary>
        /// Used to track the state of Owner
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<SimpleUser?> OwnerOption { get; private set; }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [JsonPropertyName("owner")]
        public SimpleUser? Owner { get { return this.OwnerOption; } set { this.OwnerOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackPlaylistMetadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<PlaylistMetadata?> FallbackPlaylistMetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackPlaylistMetadata
        /// </summary>
        [JsonPropertyName("fallback_playlist_metadata")]
        public PlaylistMetadata? FallbackPlaylistMetadata { get { return this.FallbackPlaylistMetadataOption; } set { this.FallbackPlaylistMetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FullListeningSession {\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  FallbackPlaylistMetadata: ").Append(FallbackPlaylistMetadata).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  JoinId: ").Append(JoinId).Append("\n");
            sb.Append("  QueuePlaylistId: ").Append(QueuePlaylistId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  FallbackPlaylistId: ").Append(FallbackPlaylistId).Append("\n");
            sb.Append("  FallbackPlaylistShuffle: ").Append(FallbackPlaylistShuffle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FullListeningSession" />
    /// </summary>
    public class FullListeningSessionJsonConverter : JsonConverter<FullListeningSession>
    {
        /// <summary>
        /// Deserializes json to <see cref="FullListeningSession" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FullListeningSession Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<bool?> active = default;
            Option<long?> ownerId = default;
            Option<string?> joinId = default;
            Option<string?> queuePlaylistId = default;
            Option<string?> title = default;
            Option<string?> fallbackPlaylistId = default;
            Option<bool?> fallbackPlaylistShuffle = default;
            Option<SimpleUser?> owner = default;
            Option<PlaylistMetadata?> fallbackPlaylistMetadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "active":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                active = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "owner_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                ownerId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "join_id":
                            joinId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "queue_playlist_id":
                            queuePlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fallback_playlist_id":
                            fallbackPlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fallback_playlist_shuffle":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                fallbackPlaylistShuffle = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "owner":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                owner = new Option<SimpleUser?>(JsonSerializer.Deserialize<SimpleUser>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        case "fallback_playlist_metadata":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                fallbackPlaylistMetadata = new Option<PlaylistMetadata?>(JsonSerializer.Deserialize<PlaylistMetadata>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class FullListeningSession.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class FullListeningSession.");

            if (ownerId.IsSet && ownerId.Value == null)
                throw new ArgumentNullException(nameof(ownerId), "Property is not nullable for class FullListeningSession.");

            if (joinId.IsSet && joinId.Value == null)
                throw new ArgumentNullException(nameof(joinId), "Property is not nullable for class FullListeningSession.");

            if (queuePlaylistId.IsSet && queuePlaylistId.Value == null)
                throw new ArgumentNullException(nameof(queuePlaylistId), "Property is not nullable for class FullListeningSession.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class FullListeningSession.");

            if (fallbackPlaylistShuffle.IsSet && fallbackPlaylistShuffle.Value == null)
                throw new ArgumentNullException(nameof(fallbackPlaylistShuffle), "Property is not nullable for class FullListeningSession.");

            if (owner.IsSet && owner.Value == null)
                throw new ArgumentNullException(nameof(owner), "Property is not nullable for class FullListeningSession.");

            return new FullListeningSession(id, active, ownerId, joinId, queuePlaylistId, title, fallbackPlaylistId, fallbackPlaylistShuffle, owner, fallbackPlaylistMetadata);
        }

        /// <summary>
        /// Serializes a <see cref="FullListeningSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullListeningSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FullListeningSession fullListeningSession, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fullListeningSession, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FullListeningSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullListeningSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FullListeningSession fullListeningSession, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fullListeningSession.JoinIdOption.IsSet && fullListeningSession.JoinId == null)
                throw new ArgumentNullException(nameof(fullListeningSession.JoinId), "Property is required for class FullListeningSession.");

            if (fullListeningSession.QueuePlaylistIdOption.IsSet && fullListeningSession.QueuePlaylistId == null)
                throw new ArgumentNullException(nameof(fullListeningSession.QueuePlaylistId), "Property is required for class FullListeningSession.");

            if (fullListeningSession.TitleOption.IsSet && fullListeningSession.Title == null)
                throw new ArgumentNullException(nameof(fullListeningSession.Title), "Property is required for class FullListeningSession.");

            if (fullListeningSession.FallbackPlaylistIdOption.IsSet && fullListeningSession.FallbackPlaylistId == null)
                throw new ArgumentNullException(nameof(fullListeningSession.FallbackPlaylistId), "Property is required for class FullListeningSession.");

            if (fullListeningSession.OwnerOption.IsSet && fullListeningSession.Owner == null)
                throw new ArgumentNullException(nameof(fullListeningSession.Owner), "Property is required for class FullListeningSession.");

            if (fullListeningSession.FallbackPlaylistMetadataOption.IsSet && fullListeningSession.FallbackPlaylistMetadata == null)
                throw new ArgumentNullException(nameof(fullListeningSession.FallbackPlaylistMetadata), "Property is required for class FullListeningSession.");

            if (fullListeningSession.IdOption.IsSet)
                writer.WriteNumber("id", fullListeningSession.IdOption.Value!.Value);

            if (fullListeningSession.ActiveOption.IsSet)
                writer.WriteBoolean("active", fullListeningSession.ActiveOption.Value!.Value);

            if (fullListeningSession.OwnerIdOption.IsSet)
                writer.WriteNumber("owner_id", fullListeningSession.OwnerIdOption.Value!.Value);

            if (fullListeningSession.JoinIdOption.IsSet)
                writer.WriteString("join_id", fullListeningSession.JoinId);

            if (fullListeningSession.QueuePlaylistIdOption.IsSet)
                writer.WriteString("queue_playlist_id", fullListeningSession.QueuePlaylistId);

            if (fullListeningSession.TitleOption.IsSet)
                writer.WriteString("title", fullListeningSession.Title);

            if (fullListeningSession.FallbackPlaylistIdOption.IsSet)
                writer.WriteString("fallback_playlist_id", fullListeningSession.FallbackPlaylistId);

            if (fullListeningSession.FallbackPlaylistShuffleOption.IsSet)
                writer.WriteBoolean("fallback_playlist_shuffle", fullListeningSession.FallbackPlaylistShuffleOption.Value!.Value);

            if (fullListeningSession.OwnerOption.IsSet)
            {
                writer.WritePropertyName("owner");
                JsonSerializer.Serialize(writer, fullListeningSession.Owner, jsonSerializerOptions);
            }
            if (fullListeningSession.FallbackPlaylistMetadataOption.IsSet)
            {
                writer.WritePropertyName("fallback_playlist_metadata");
                JsonSerializer.Serialize(writer, fullListeningSession.FallbackPlaylistMetadata, jsonSerializerOptions);
            }
        }
    }
}
