// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// FullUser
    /// </summary>
    public partial class FullUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FullUser" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="spotifyId">spotifyId</param>
        /// <param name="spotifyDisplayName">spotifyDisplayName</param>
        /// <param name="name">name</param>
        /// <param name="listeningSessions">listeningSessions</param>
        [JsonConstructor]
        public FullUser(Option<int?> id = default, Option<string?> spotifyId = default, Option<string?> spotifyDisplayName = default, Option<string?> name = default, Option<List<SimpleListeningSession>?> listeningSessions = default)
        {
            IdOption = id;
            SpotifyIdOption = spotifyId;
            SpotifyDisplayNameOption = spotifyDisplayName;
            NameOption = name;
            ListeningSessionsOption = listeningSessions;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyId
        /// </summary>
        [JsonPropertyName("spotify_id")]
        public string? SpotifyId { get { return this.SpotifyIdOption; } set { this.SpotifyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyDisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyDisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyDisplayName
        /// </summary>
        [JsonPropertyName("spotify_display_name")]
        public string? SpotifyDisplayName { get { return this.SpotifyDisplayNameOption; } set { this.SpotifyDisplayNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ListeningSessions
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SimpleListeningSession>?> ListeningSessionsOption { get; private set; }

        /// <summary>
        /// Gets or Sets ListeningSessions
        /// </summary>
        [JsonPropertyName("listening_sessions")]
        public List<SimpleListeningSession>? ListeningSessions { get { return this.ListeningSessionsOption; } set { this.ListeningSessionsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class FullUser {\n");
            sb.Append("  ListeningSessions: ").Append(ListeningSessions).Append("\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SpotifyId: ").Append(SpotifyId).Append("\n");
            sb.Append("  SpotifyDisplayName: ").Append(SpotifyDisplayName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="FullUser" />
    /// </summary>
    public class FullUserJsonConverter : JsonConverter<FullUser>
    {
        /// <summary>
        /// Deserializes json to <see cref="FullUser" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override FullUser Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> spotifyId = default;
            Option<string?> spotifyDisplayName = default;
            Option<string?> name = default;
            Option<List<SimpleListeningSession>?> listeningSessions = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "spotify_id":
                            spotifyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "spotify_display_name":
                            spotifyDisplayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "listening_sessions":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                listeningSessions = new Option<List<SimpleListeningSession>?>(JsonSerializer.Deserialize<List<SimpleListeningSession>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class FullUser.");

            if (spotifyId.IsSet && spotifyId.Value == null)
                throw new ArgumentNullException(nameof(spotifyId), "Property is not nullable for class FullUser.");

            if (spotifyDisplayName.IsSet && spotifyDisplayName.Value == null)
                throw new ArgumentNullException(nameof(spotifyDisplayName), "Property is not nullable for class FullUser.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class FullUser.");

            if (listeningSessions.IsSet && listeningSessions.Value == null)
                throw new ArgumentNullException(nameof(listeningSessions), "Property is not nullable for class FullUser.");

            return new FullUser(id, spotifyId, spotifyDisplayName, name, listeningSessions);
        }

        /// <summary>
        /// Serializes a <see cref="FullUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, FullUser fullUser, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, fullUser, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="FullUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="fullUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, FullUser fullUser, JsonSerializerOptions jsonSerializerOptions)
        {
            if (fullUser.SpotifyIdOption.IsSet && fullUser.SpotifyId == null)
                throw new ArgumentNullException(nameof(fullUser.SpotifyId), "Property is required for class FullUser.");

            if (fullUser.SpotifyDisplayNameOption.IsSet && fullUser.SpotifyDisplayName == null)
                throw new ArgumentNullException(nameof(fullUser.SpotifyDisplayName), "Property is required for class FullUser.");

            if (fullUser.NameOption.IsSet && fullUser.Name == null)
                throw new ArgumentNullException(nameof(fullUser.Name), "Property is required for class FullUser.");

            if (fullUser.ListeningSessionsOption.IsSet && fullUser.ListeningSessions == null)
                throw new ArgumentNullException(nameof(fullUser.ListeningSessions), "Property is required for class FullUser.");

            if (fullUser.IdOption.IsSet)
                writer.WriteNumber("id", fullUser.IdOption.Value!.Value);

            if (fullUser.SpotifyIdOption.IsSet)
                writer.WriteString("spotify_id", fullUser.SpotifyId);

            if (fullUser.SpotifyDisplayNameOption.IsSet)
                writer.WriteString("spotify_display_name", fullUser.SpotifyDisplayName);

            if (fullUser.NameOption.IsSet)
                writer.WriteString("name", fullUser.Name);

            if (fullUser.ListeningSessionsOption.IsSet)
            {
                writer.WritePropertyName("listening_sessions");
                JsonSerializer.Serialize(writer, fullUser.ListeningSessions, jsonSerializerOptions);
            }
        }
    }
}
