// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// GetSessionQueueResponse
    /// </summary>
    public partial class GetSessionQueueResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetSessionQueueResponse" /> class.
        /// </summary>
        /// <param name="queue">queue</param>
        [JsonConstructor]
        public GetSessionQueueResponse(Option<List<SongRequest>?> queue = default)
        {
            QueueOption = queue;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Queue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<SongRequest>?> QueueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Queue
        /// </summary>
        [JsonPropertyName("queue")]
        public List<SongRequest>? Queue { get { return this.QueueOption; } set { this.QueueOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GetSessionQueueResponse {\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="GetSessionQueueResponse" />
    /// </summary>
    public class GetSessionQueueResponseJsonConverter : JsonConverter<GetSessionQueueResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="GetSessionQueueResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override GetSessionQueueResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<List<SongRequest>?> queue = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "queue":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                queue = new Option<List<SongRequest>?>(JsonSerializer.Deserialize<List<SongRequest>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (queue.IsSet && queue.Value == null)
                throw new ArgumentNullException(nameof(queue), "Property is not nullable for class GetSessionQueueResponse.");

            return new GetSessionQueueResponse(queue);
        }

        /// <summary>
        /// Serializes a <see cref="GetSessionQueueResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSessionQueueResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, GetSessionQueueResponse getSessionQueueResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, getSessionQueueResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="GetSessionQueueResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="getSessionQueueResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, GetSessionQueueResponse getSessionQueueResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (getSessionQueueResponse.QueueOption.IsSet && getSessionQueueResponse.Queue == null)
                throw new ArgumentNullException(nameof(getSessionQueueResponse.Queue), "Property is required for class GetSessionQueueResponse.");

            if (getSessionQueueResponse.QueueOption.IsSet)
            {
                writer.WritePropertyName("queue");
                JsonSerializer.Serialize(writer, getSessionQueueResponse.Queue, jsonSerializerOptions);
            }
        }
    }
}
