// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// NewAuthenticationSessionResponse
    /// </summary>
    public partial class NewAuthenticationSessionResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewAuthenticationSessionResponse" /> class.
        /// </summary>
        /// <param name="spotifyAuthenticationUrl">spotifyAuthenticationUrl</param>
        /// <param name="spotifeteSessionId">spotifeteSessionId</param>
        [JsonConstructor]
        public NewAuthenticationSessionResponse(Option<string?> spotifyAuthenticationUrl = default, Option<string?> spotifeteSessionId = default)
        {
            SpotifyAuthenticationUrlOption = spotifyAuthenticationUrl;
            SpotifeteSessionIdOption = spotifeteSessionId;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SpotifyAuthenticationUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyAuthenticationUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyAuthenticationUrl
        /// </summary>
        [JsonPropertyName("spotify_authentication_url")]
        public string? SpotifyAuthenticationUrl { get { return this.SpotifyAuthenticationUrlOption; } set { this.SpotifyAuthenticationUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifeteSessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifeteSessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifeteSessionId
        /// </summary>
        [JsonPropertyName("spotifete_session_id")]
        public string? SpotifeteSessionId { get { return this.SpotifeteSessionIdOption; } set { this.SpotifeteSessionIdOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewAuthenticationSessionResponse {\n");
            sb.Append("  SpotifyAuthenticationUrl: ").Append(SpotifyAuthenticationUrl).Append("\n");
            sb.Append("  SpotifeteSessionId: ").Append(SpotifeteSessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewAuthenticationSessionResponse" />
    /// </summary>
    public class NewAuthenticationSessionResponseJsonConverter : JsonConverter<NewAuthenticationSessionResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="NewAuthenticationSessionResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewAuthenticationSessionResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> spotifyAuthenticationUrl = default;
            Option<string?> spotifeteSessionId = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "spotify_authentication_url":
                            spotifyAuthenticationUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "spotifete_session_id":
                            spotifeteSessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (spotifyAuthenticationUrl.IsSet && spotifyAuthenticationUrl.Value == null)
                throw new ArgumentNullException(nameof(spotifyAuthenticationUrl), "Property is not nullable for class NewAuthenticationSessionResponse.");

            if (spotifeteSessionId.IsSet && spotifeteSessionId.Value == null)
                throw new ArgumentNullException(nameof(spotifeteSessionId), "Property is not nullable for class NewAuthenticationSessionResponse.");

            return new NewAuthenticationSessionResponse(spotifyAuthenticationUrl, spotifeteSessionId);
        }

        /// <summary>
        /// Serializes a <see cref="NewAuthenticationSessionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newAuthenticationSessionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NewAuthenticationSessionResponse newAuthenticationSessionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newAuthenticationSessionResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewAuthenticationSessionResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newAuthenticationSessionResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NewAuthenticationSessionResponse newAuthenticationSessionResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (newAuthenticationSessionResponse.SpotifyAuthenticationUrlOption.IsSet && newAuthenticationSessionResponse.SpotifyAuthenticationUrl == null)
                throw new ArgumentNullException(nameof(newAuthenticationSessionResponse.SpotifyAuthenticationUrl), "Property is required for class NewAuthenticationSessionResponse.");

            if (newAuthenticationSessionResponse.SpotifeteSessionIdOption.IsSet && newAuthenticationSessionResponse.SpotifeteSessionId == null)
                throw new ArgumentNullException(nameof(newAuthenticationSessionResponse.SpotifeteSessionId), "Property is required for class NewAuthenticationSessionResponse.");

            if (newAuthenticationSessionResponse.SpotifyAuthenticationUrlOption.IsSet)
                writer.WriteString("spotify_authentication_url", newAuthenticationSessionResponse.SpotifyAuthenticationUrl);

            if (newAuthenticationSessionResponse.SpotifeteSessionIdOption.IsSet)
                writer.WriteString("spotifete_session_id", newAuthenticationSessionResponse.SpotifeteSessionId);
        }
    }
}
