// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// NewListeningSessionRequest
    /// </summary>
    public partial class NewListeningSessionRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NewListeningSessionRequest" /> class.
        /// </summary>
        /// <param name="loginSessionId">loginSessionId</param>
        /// <param name="listeningSessionTitle">listeningSessionTitle</param>
        [JsonConstructor]
        public NewListeningSessionRequest(Option<string?> loginSessionId = default, Option<string?> listeningSessionTitle = default)
        {
            LoginSessionIdOption = loginSessionId;
            ListeningSessionTitleOption = listeningSessionTitle;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LoginSessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LoginSessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LoginSessionId
        /// </summary>
        [JsonPropertyName("login_session_id")]
        public string? LoginSessionId { get { return this.LoginSessionIdOption; } set { this.LoginSessionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of ListeningSessionTitle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ListeningSessionTitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets ListeningSessionTitle
        /// </summary>
        [JsonPropertyName("listening_session_title")]
        public string? ListeningSessionTitle { get { return this.ListeningSessionTitleOption; } set { this.ListeningSessionTitleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class NewListeningSessionRequest {\n");
            sb.Append("  ListeningSessionTitle: ").Append(ListeningSessionTitle).Append("\n");
            sb.Append("  LoginSessionId: ").Append(LoginSessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="NewListeningSessionRequest" />
    /// </summary>
    public class NewListeningSessionRequestJsonConverter : JsonConverter<NewListeningSessionRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="NewListeningSessionRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override NewListeningSessionRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> loginSessionId = default;
            Option<string?> listeningSessionTitle = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "login_session_id":
                            loginSessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "listening_session_title":
                            listeningSessionTitle = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (loginSessionId.IsSet && loginSessionId.Value == null)
                throw new ArgumentNullException(nameof(loginSessionId), "Property is not nullable for class NewListeningSessionRequest.");

            if (listeningSessionTitle.IsSet && listeningSessionTitle.Value == null)
                throw new ArgumentNullException(nameof(listeningSessionTitle), "Property is not nullable for class NewListeningSessionRequest.");

            return new NewListeningSessionRequest(loginSessionId, listeningSessionTitle);
        }

        /// <summary>
        /// Serializes a <see cref="NewListeningSessionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newListeningSessionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, NewListeningSessionRequest newListeningSessionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, newListeningSessionRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="NewListeningSessionRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="newListeningSessionRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, NewListeningSessionRequest newListeningSessionRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (newListeningSessionRequest.LoginSessionIdOption.IsSet && newListeningSessionRequest.LoginSessionId == null)
                throw new ArgumentNullException(nameof(newListeningSessionRequest.LoginSessionId), "Property is required for class NewListeningSessionRequest.");

            if (newListeningSessionRequest.ListeningSessionTitleOption.IsSet && newListeningSessionRequest.ListeningSessionTitle == null)
                throw new ArgumentNullException(nameof(newListeningSessionRequest.ListeningSessionTitle), "Property is required for class NewListeningSessionRequest.");

            if (newListeningSessionRequest.LoginSessionIdOption.IsSet)
                writer.WriteString("login_session_id", newListeningSessionRequest.LoginSessionId);

            if (newListeningSessionRequest.ListeningSessionTitleOption.IsSet)
                writer.WriteString("listening_session_title", newListeningSessionRequest.ListeningSessionTitle);
        }
    }
}
