// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PlaylistMetadata
    /// </summary>
    public partial class PlaylistMetadata : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PlaylistMetadata" /> class.
        /// </summary>
        /// <param name="spotifyPlaylistId">spotifyPlaylistId</param>
        /// <param name="name">name</param>
        /// <param name="trackCount">trackCount</param>
        /// <param name="imageThumbnailUrl">imageThumbnailUrl</param>
        /// <param name="ownerName">ownerName</param>
        [JsonConstructor]
        public PlaylistMetadata(Option<string?> spotifyPlaylistId = default, Option<string?> name = default, Option<int?> trackCount = default, Option<string?> imageThumbnailUrl = default, Option<string?> ownerName = default)
        {
            SpotifyPlaylistIdOption = spotifyPlaylistId;
            NameOption = name;
            TrackCountOption = trackCount;
            ImageThumbnailUrlOption = imageThumbnailUrl;
            OwnerNameOption = ownerName;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SpotifyPlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyPlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyPlaylistId
        /// </summary>
        [JsonPropertyName("spotify_playlist_id")]
        public string? SpotifyPlaylistId { get { return this.SpotifyPlaylistIdOption; } set { this.SpotifyPlaylistIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrackCount
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> TrackCountOption { get; private set; }

        /// <summary>
        /// Gets or Sets TrackCount
        /// </summary>
        [JsonPropertyName("track_count")]
        public int? TrackCount { get { return this.TrackCountOption; } set { this.TrackCountOption = new(value); } }

        /// <summary>
        /// Used to track the state of ImageThumbnailUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ImageThumbnailUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets ImageThumbnailUrl
        /// </summary>
        [JsonPropertyName("image_thumbnail_url")]
        public string? ImageThumbnailUrl { get { return this.ImageThumbnailUrlOption; } set { this.ImageThumbnailUrlOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwnerName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> OwnerNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwnerName
        /// </summary>
        [JsonPropertyName("owner_name")]
        public string? OwnerName { get { return this.OwnerNameOption; } set { this.OwnerNameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PlaylistMetadata {\n");
            sb.Append("  SpotifyPlaylistId: ").Append(SpotifyPlaylistId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  TrackCount: ").Append(TrackCount).Append("\n");
            sb.Append("  ImageThumbnailUrl: ").Append(ImageThumbnailUrl).Append("\n");
            sb.Append("  OwnerName: ").Append(OwnerName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="PlaylistMetadata" />
    /// </summary>
    public class PlaylistMetadataJsonConverter : JsonConverter<PlaylistMetadata>
    {
        /// <summary>
        /// Deserializes json to <see cref="PlaylistMetadata" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override PlaylistMetadata Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> spotifyPlaylistId = default;
            Option<string?> name = default;
            Option<int?> trackCount = default;
            Option<string?> imageThumbnailUrl = default;
            Option<string?> ownerName = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "spotify_playlist_id":
                            spotifyPlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "track_count":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                trackCount = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "image_thumbnail_url":
                            imageThumbnailUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "owner_name":
                            ownerName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (spotifyPlaylistId.IsSet && spotifyPlaylistId.Value == null)
                throw new ArgumentNullException(nameof(spotifyPlaylistId), "Property is not nullable for class PlaylistMetadata.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class PlaylistMetadata.");

            if (trackCount.IsSet && trackCount.Value == null)
                throw new ArgumentNullException(nameof(trackCount), "Property is not nullable for class PlaylistMetadata.");

            if (imageThumbnailUrl.IsSet && imageThumbnailUrl.Value == null)
                throw new ArgumentNullException(nameof(imageThumbnailUrl), "Property is not nullable for class PlaylistMetadata.");

            if (ownerName.IsSet && ownerName.Value == null)
                throw new ArgumentNullException(nameof(ownerName), "Property is not nullable for class PlaylistMetadata.");

            return new PlaylistMetadata(spotifyPlaylistId, name, trackCount, imageThumbnailUrl, ownerName);
        }

        /// <summary>
        /// Serializes a <see cref="PlaylistMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playlistMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, PlaylistMetadata playlistMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, playlistMetadata, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="PlaylistMetadata" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="playlistMetadata"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, PlaylistMetadata playlistMetadata, JsonSerializerOptions jsonSerializerOptions)
        {
            if (playlistMetadata.SpotifyPlaylistIdOption.IsSet && playlistMetadata.SpotifyPlaylistId == null)
                throw new ArgumentNullException(nameof(playlistMetadata.SpotifyPlaylistId), "Property is required for class PlaylistMetadata.");

            if (playlistMetadata.NameOption.IsSet && playlistMetadata.Name == null)
                throw new ArgumentNullException(nameof(playlistMetadata.Name), "Property is required for class PlaylistMetadata.");

            if (playlistMetadata.ImageThumbnailUrlOption.IsSet && playlistMetadata.ImageThumbnailUrl == null)
                throw new ArgumentNullException(nameof(playlistMetadata.ImageThumbnailUrl), "Property is required for class PlaylistMetadata.");

            if (playlistMetadata.OwnerNameOption.IsSet && playlistMetadata.OwnerName == null)
                throw new ArgumentNullException(nameof(playlistMetadata.OwnerName), "Property is required for class PlaylistMetadata.");

            if (playlistMetadata.SpotifyPlaylistIdOption.IsSet)
                writer.WriteString("spotify_playlist_id", playlistMetadata.SpotifyPlaylistId);

            if (playlistMetadata.NameOption.IsSet)
                writer.WriteString("name", playlistMetadata.Name);

            if (playlistMetadata.TrackCountOption.IsSet)
                writer.WriteNumber("track_count", playlistMetadata.TrackCountOption.Value!.Value);

            if (playlistMetadata.ImageThumbnailUrlOption.IsSet)
                writer.WriteString("image_thumbnail_url", playlistMetadata.ImageThumbnailUrl);

            if (playlistMetadata.OwnerNameOption.IsSet)
                writer.WriteString("owner_name", playlistMetadata.OwnerName);
        }
    }
}
