// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// QueueLastUpdatedResponse
    /// </summary>
    public partial class QueueLastUpdatedResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="QueueLastUpdatedResponse" /> class.
        /// </summary>
        /// <param name="queueLastUpdated">queueLastUpdated</param>
        [JsonConstructor]
        public QueueLastUpdatedResponse(Option<DateTime?> queueLastUpdated = default)
        {
            QueueLastUpdatedOption = queueLastUpdated;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of QueueLastUpdated
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<DateTime?> QueueLastUpdatedOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueueLastUpdated
        /// </summary>
        [JsonPropertyName("queue_last_updated")]
        public DateTime? QueueLastUpdated { get { return this.QueueLastUpdatedOption; } set { this.QueueLastUpdatedOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class QueueLastUpdatedResponse {\n");
            sb.Append("  QueueLastUpdated: ").Append(QueueLastUpdated).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="QueueLastUpdatedResponse" />
    /// </summary>
    public class QueueLastUpdatedResponseJsonConverter : JsonConverter<QueueLastUpdatedResponse>
    {
        /// <summary>
        /// The format to use to serialize QueueLastUpdated
        /// </summary>
        public static string QueueLastUpdatedFormat { get; set; } = "yyyy'-'MM'-'dd'T'HH':'mm':'ss'.'fffffffK";

        /// <summary>
        /// Deserializes json to <see cref="QueueLastUpdatedResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override QueueLastUpdatedResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<DateTime?> queueLastUpdated = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "queue_last_updated":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                queueLastUpdated = new Option<DateTime?>(JsonSerializer.Deserialize<DateTime>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (queueLastUpdated.IsSet && queueLastUpdated.Value == null)
                throw new ArgumentNullException(nameof(queueLastUpdated), "Property is not nullable for class QueueLastUpdatedResponse.");

            return new QueueLastUpdatedResponse(queueLastUpdated);
        }

        /// <summary>
        /// Serializes a <see cref="QueueLastUpdatedResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queueLastUpdatedResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, QueueLastUpdatedResponse queueLastUpdatedResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, queueLastUpdatedResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="QueueLastUpdatedResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="queueLastUpdatedResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, QueueLastUpdatedResponse queueLastUpdatedResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (queueLastUpdatedResponse.QueueLastUpdatedOption.IsSet)
                writer.WriteString("queue_last_updated", queueLastUpdatedResponse.QueueLastUpdatedOption.Value!.Value.ToString(QueueLastUpdatedFormat));
        }
    }
}
