// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchPlaylistResponse
    /// </summary>
    public partial class SearchPlaylistResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchPlaylistResponse" /> class.
        /// </summary>
        /// <param name="queue">queue</param>
        /// <param name="playlists">playlists</param>
        [JsonConstructor]
        public SearchPlaylistResponse(Option<string?> queue = default, Option<List<PlaylistMetadata>?> playlists = default)
        {
            QueueOption = queue;
            PlaylistsOption = playlists;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Queue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Queue
        /// </summary>
        [JsonPropertyName("queue")]
        public string? Queue { get { return this.QueueOption; } set { this.QueueOption = new(value); } }

        /// <summary>
        /// Used to track the state of Playlists
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<PlaylistMetadata>?> PlaylistsOption { get; private set; }

        /// <summary>
        /// Gets or Sets Playlists
        /// </summary>
        [JsonPropertyName("playlists")]
        public List<PlaylistMetadata>? Playlists { get { return this.PlaylistsOption; } set { this.PlaylistsOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchPlaylistResponse {\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("  Playlists: ").Append(Playlists).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchPlaylistResponse" />
    /// </summary>
    public class SearchPlaylistResponseJsonConverter : JsonConverter<SearchPlaylistResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchPlaylistResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchPlaylistResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> queue = default;
            Option<List<PlaylistMetadata>?> playlists = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "queue":
                            queue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "playlists":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                playlists = new Option<List<PlaylistMetadata>?>(JsonSerializer.Deserialize<List<PlaylistMetadata>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (queue.IsSet && queue.Value == null)
                throw new ArgumentNullException(nameof(queue), "Property is not nullable for class SearchPlaylistResponse.");

            if (playlists.IsSet && playlists.Value == null)
                throw new ArgumentNullException(nameof(playlists), "Property is not nullable for class SearchPlaylistResponse.");

            return new SearchPlaylistResponse(queue, playlists);
        }

        /// <summary>
        /// Serializes a <see cref="SearchPlaylistResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchPlaylistResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchPlaylistResponse searchPlaylistResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchPlaylistResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchPlaylistResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchPlaylistResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchPlaylistResponse searchPlaylistResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchPlaylistResponse.QueueOption.IsSet && searchPlaylistResponse.Queue == null)
                throw new ArgumentNullException(nameof(searchPlaylistResponse.Queue), "Property is required for class SearchPlaylistResponse.");

            if (searchPlaylistResponse.PlaylistsOption.IsSet && searchPlaylistResponse.Playlists == null)
                throw new ArgumentNullException(nameof(searchPlaylistResponse.Playlists), "Property is required for class SearchPlaylistResponse.");

            if (searchPlaylistResponse.QueueOption.IsSet)
                writer.WriteString("queue", searchPlaylistResponse.Queue);

            if (searchPlaylistResponse.PlaylistsOption.IsSet)
            {
                writer.WritePropertyName("playlists");
                JsonSerializer.Serialize(writer, searchPlaylistResponse.Playlists, jsonSerializerOptions);
            }
        }
    }
}
