// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SearchTracksResponse
    /// </summary>
    public partial class SearchTracksResponse : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchTracksResponse" /> class.
        /// </summary>
        /// <param name="queue">queue</param>
        /// <param name="tracks">tracks</param>
        [JsonConstructor]
        public SearchTracksResponse(Option<string?> queue = default, Option<List<TrackMetaData>?> tracks = default)
        {
            QueueOption = queue;
            TracksOption = tracks;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Queue
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueueOption { get; private set; }

        /// <summary>
        /// Gets or Sets Queue
        /// </summary>
        [JsonPropertyName("queue")]
        public string? Queue { get { return this.QueueOption; } set { this.QueueOption = new(value); } }

        /// <summary>
        /// Used to track the state of Tracks
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<List<TrackMetaData>?> TracksOption { get; private set; }

        /// <summary>
        /// Gets or Sets Tracks
        /// </summary>
        [JsonPropertyName("tracks")]
        public List<TrackMetaData>? Tracks { get { return this.TracksOption; } set { this.TracksOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SearchTracksResponse {\n");
            sb.Append("  Queue: ").Append(Queue).Append("\n");
            sb.Append("  Tracks: ").Append(Tracks).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SearchTracksResponse" />
    /// </summary>
    public class SearchTracksResponseJsonConverter : JsonConverter<SearchTracksResponse>
    {
        /// <summary>
        /// Deserializes json to <see cref="SearchTracksResponse" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SearchTracksResponse Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> queue = default;
            Option<List<TrackMetaData>?> tracks = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "queue":
                            queue = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "tracks":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                tracks = new Option<List<TrackMetaData>?>(JsonSerializer.Deserialize<List<TrackMetaData>>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (queue.IsSet && queue.Value == null)
                throw new ArgumentNullException(nameof(queue), "Property is not nullable for class SearchTracksResponse.");

            if (tracks.IsSet && tracks.Value == null)
                throw new ArgumentNullException(nameof(tracks), "Property is not nullable for class SearchTracksResponse.");

            return new SearchTracksResponse(queue, tracks);
        }

        /// <summary>
        /// Serializes a <see cref="SearchTracksResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchTracksResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SearchTracksResponse searchTracksResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, searchTracksResponse, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SearchTracksResponse" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="searchTracksResponse"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SearchTracksResponse searchTracksResponse, JsonSerializerOptions jsonSerializerOptions)
        {
            if (searchTracksResponse.QueueOption.IsSet && searchTracksResponse.Queue == null)
                throw new ArgumentNullException(nameof(searchTracksResponse.Queue), "Property is required for class SearchTracksResponse.");

            if (searchTracksResponse.TracksOption.IsSet && searchTracksResponse.Tracks == null)
                throw new ArgumentNullException(nameof(searchTracksResponse.Tracks), "Property is required for class SearchTracksResponse.");

            if (searchTracksResponse.QueueOption.IsSet)
                writer.WriteString("queue", searchTracksResponse.Queue);

            if (searchTracksResponse.TracksOption.IsSet)
            {
                writer.WritePropertyName("tracks");
                JsonSerializer.Serialize(writer, searchTracksResponse.Tracks, jsonSerializerOptions);
            }
        }
    }
}
