// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SetFallbackPlaylistShuffleRequest
    /// </summary>
    public partial class SetFallbackPlaylistShuffleRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SetFallbackPlaylistShuffleRequest" /> class.
        /// </summary>
        /// <param name="loginSessionId">loginSessionId</param>
        /// <param name="shuffle">shuffle</param>
        [JsonConstructor]
        public SetFallbackPlaylistShuffleRequest(Option<string?> loginSessionId = default, Option<bool?> shuffle = default)
        {
            LoginSessionIdOption = loginSessionId;
            ShuffleOption = shuffle;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of LoginSessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> LoginSessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets LoginSessionId
        /// </summary>
        [JsonPropertyName("login_session_id")]
        public string? LoginSessionId { get { return this.LoginSessionIdOption; } set { this.LoginSessionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Shuffle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ShuffleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Shuffle
        /// </summary>
        [JsonPropertyName("shuffle")]
        public bool? Shuffle { get { return this.ShuffleOption; } set { this.ShuffleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SetFallbackPlaylistShuffleRequest {\n");
            sb.Append("  Shuffle: ").Append(Shuffle).Append("\n");
            sb.Append("  LoginSessionId: ").Append(LoginSessionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SetFallbackPlaylistShuffleRequest" />
    /// </summary>
    public class SetFallbackPlaylistShuffleRequestJsonConverter : JsonConverter<SetFallbackPlaylistShuffleRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SetFallbackPlaylistShuffleRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SetFallbackPlaylistShuffleRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> loginSessionId = default;
            Option<bool?> shuffle = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "login_session_id":
                            loginSessionId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "shuffle":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                shuffle = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (loginSessionId.IsSet && loginSessionId.Value == null)
                throw new ArgumentNullException(nameof(loginSessionId), "Property is not nullable for class SetFallbackPlaylistShuffleRequest.");

            if (shuffle.IsSet && shuffle.Value == null)
                throw new ArgumentNullException(nameof(shuffle), "Property is not nullable for class SetFallbackPlaylistShuffleRequest.");

            return new SetFallbackPlaylistShuffleRequest(loginSessionId, shuffle);
        }

        /// <summary>
        /// Serializes a <see cref="SetFallbackPlaylistShuffleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setFallbackPlaylistShuffleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SetFallbackPlaylistShuffleRequest setFallbackPlaylistShuffleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, setFallbackPlaylistShuffleRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SetFallbackPlaylistShuffleRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="setFallbackPlaylistShuffleRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SetFallbackPlaylistShuffleRequest setFallbackPlaylistShuffleRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (setFallbackPlaylistShuffleRequest.LoginSessionIdOption.IsSet && setFallbackPlaylistShuffleRequest.LoginSessionId == null)
                throw new ArgumentNullException(nameof(setFallbackPlaylistShuffleRequest.LoginSessionId), "Property is required for class SetFallbackPlaylistShuffleRequest.");

            if (setFallbackPlaylistShuffleRequest.LoginSessionIdOption.IsSet)
                writer.WriteString("login_session_id", setFallbackPlaylistShuffleRequest.LoginSessionId);

            if (setFallbackPlaylistShuffleRequest.ShuffleOption.IsSet)
                writer.WriteBoolean("shuffle", setFallbackPlaylistShuffleRequest.ShuffleOption.Value!.Value);
        }
    }
}
