// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SimpleListeningSession
    /// </summary>
    public partial class SimpleListeningSession : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleListeningSession" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="active">active</param>
        /// <param name="ownerId">ownerId</param>
        /// <param name="joinId">joinId</param>
        /// <param name="queuePlaylistId">queuePlaylistId</param>
        /// <param name="title">title</param>
        /// <param name="fallbackPlaylistId">fallbackPlaylistId</param>
        /// <param name="fallbackPlaylistShuffle">fallbackPlaylistShuffle</param>
        [JsonConstructor]
        public SimpleListeningSession(Option<long?> id = default, Option<bool?> active = default, Option<long?> ownerId = default, Option<string?> joinId = default, Option<string?> queuePlaylistId = default, Option<string?> title = default, Option<string?> fallbackPlaylistId = default, Option<bool?> fallbackPlaylistShuffle = default)
        {
            IdOption = id;
            ActiveOption = active;
            OwnerIdOption = ownerId;
            JoinIdOption = joinId;
            QueuePlaylistIdOption = queuePlaylistId;
            TitleOption = title;
            FallbackPlaylistIdOption = fallbackPlaylistId;
            FallbackPlaylistShuffleOption = fallbackPlaylistShuffle;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public long? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Active
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> ActiveOption { get; private set; }

        /// <summary>
        /// Gets or Sets Active
        /// </summary>
        [JsonPropertyName("active")]
        public bool? Active { get { return this.ActiveOption; } set { this.ActiveOption = new(value); } }

        /// <summary>
        /// Used to track the state of OwnerId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> OwnerIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets OwnerId
        /// </summary>
        [JsonPropertyName("owner_id")]
        public long? OwnerId { get { return this.OwnerIdOption; } set { this.OwnerIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of JoinId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> JoinIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets JoinId
        /// </summary>
        [JsonPropertyName("join_id")]
        public string? JoinId { get { return this.JoinIdOption; } set { this.JoinIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of QueuePlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> QueuePlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets QueuePlaylistId
        /// </summary>
        [JsonPropertyName("queue_playlist_id")]
        public string? QueuePlaylistId { get { return this.QueuePlaylistIdOption; } set { this.QueuePlaylistIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of Title
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TitleOption { get; private set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [JsonPropertyName("title")]
        public string? Title { get { return this.TitleOption; } set { this.TitleOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackPlaylistId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> FallbackPlaylistIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackPlaylistId
        /// </summary>
        [JsonPropertyName("fallback_playlist_id")]
        public string? FallbackPlaylistId { get { return this.FallbackPlaylistIdOption; } set { this.FallbackPlaylistIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of FallbackPlaylistShuffle
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<bool?> FallbackPlaylistShuffleOption { get; private set; }

        /// <summary>
        /// Gets or Sets FallbackPlaylistShuffle
        /// </summary>
        [JsonPropertyName("fallback_playlist_shuffle")]
        public bool? FallbackPlaylistShuffle { get { return this.FallbackPlaylistShuffleOption; } set { this.FallbackPlaylistShuffleOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimpleListeningSession {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Active: ").Append(Active).Append("\n");
            sb.Append("  OwnerId: ").Append(OwnerId).Append("\n");
            sb.Append("  JoinId: ").Append(JoinId).Append("\n");
            sb.Append("  QueuePlaylistId: ").Append(QueuePlaylistId).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  FallbackPlaylistId: ").Append(FallbackPlaylistId).Append("\n");
            sb.Append("  FallbackPlaylistShuffle: ").Append(FallbackPlaylistShuffle).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SimpleListeningSession" />
    /// </summary>
    public class SimpleListeningSessionJsonConverter : JsonConverter<SimpleListeningSession>
    {
        /// <summary>
        /// Deserializes json to <see cref="SimpleListeningSession" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SimpleListeningSession Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> id = default;
            Option<bool?> active = default;
            Option<long?> ownerId = default;
            Option<string?> joinId = default;
            Option<string?> queuePlaylistId = default;
            Option<string?> title = default;
            Option<string?> fallbackPlaylistId = default;
            Option<bool?> fallbackPlaylistShuffle = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "active":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                active = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        case "owner_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                ownerId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "join_id":
                            joinId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "queue_playlist_id":
                            queuePlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "title":
                            title = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fallback_playlist_id":
                            fallbackPlaylistId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "fallback_playlist_shuffle":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                fallbackPlaylistShuffle = new Option<bool?>(utf8JsonReader.GetBoolean());
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SimpleListeningSession.");

            if (active.IsSet && active.Value == null)
                throw new ArgumentNullException(nameof(active), "Property is not nullable for class SimpleListeningSession.");

            if (ownerId.IsSet && ownerId.Value == null)
                throw new ArgumentNullException(nameof(ownerId), "Property is not nullable for class SimpleListeningSession.");

            if (joinId.IsSet && joinId.Value == null)
                throw new ArgumentNullException(nameof(joinId), "Property is not nullable for class SimpleListeningSession.");

            if (queuePlaylistId.IsSet && queuePlaylistId.Value == null)
                throw new ArgumentNullException(nameof(queuePlaylistId), "Property is not nullable for class SimpleListeningSession.");

            if (title.IsSet && title.Value == null)
                throw new ArgumentNullException(nameof(title), "Property is not nullable for class SimpleListeningSession.");

            if (fallbackPlaylistId.IsSet && fallbackPlaylistId.Value == null)
                throw new ArgumentNullException(nameof(fallbackPlaylistId), "Property is not nullable for class SimpleListeningSession.");

            if (fallbackPlaylistShuffle.IsSet && fallbackPlaylistShuffle.Value == null)
                throw new ArgumentNullException(nameof(fallbackPlaylistShuffle), "Property is not nullable for class SimpleListeningSession.");

            return new SimpleListeningSession(id, active, ownerId, joinId, queuePlaylistId, title, fallbackPlaylistId, fallbackPlaylistShuffle);
        }

        /// <summary>
        /// Serializes a <see cref="SimpleListeningSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="simpleListeningSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SimpleListeningSession simpleListeningSession, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, simpleListeningSession, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SimpleListeningSession" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="simpleListeningSession"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SimpleListeningSession simpleListeningSession, JsonSerializerOptions jsonSerializerOptions)
        {
            if (simpleListeningSession.JoinIdOption.IsSet && simpleListeningSession.JoinId == null)
                throw new ArgumentNullException(nameof(simpleListeningSession.JoinId), "Property is required for class SimpleListeningSession.");

            if (simpleListeningSession.QueuePlaylistIdOption.IsSet && simpleListeningSession.QueuePlaylistId == null)
                throw new ArgumentNullException(nameof(simpleListeningSession.QueuePlaylistId), "Property is required for class SimpleListeningSession.");

            if (simpleListeningSession.TitleOption.IsSet && simpleListeningSession.Title == null)
                throw new ArgumentNullException(nameof(simpleListeningSession.Title), "Property is required for class SimpleListeningSession.");

            if (simpleListeningSession.FallbackPlaylistIdOption.IsSet && simpleListeningSession.FallbackPlaylistId == null)
                throw new ArgumentNullException(nameof(simpleListeningSession.FallbackPlaylistId), "Property is required for class SimpleListeningSession.");

            if (simpleListeningSession.IdOption.IsSet)
                writer.WriteNumber("id", simpleListeningSession.IdOption.Value!.Value);

            if (simpleListeningSession.ActiveOption.IsSet)
                writer.WriteBoolean("active", simpleListeningSession.ActiveOption.Value!.Value);

            if (simpleListeningSession.OwnerIdOption.IsSet)
                writer.WriteNumber("owner_id", simpleListeningSession.OwnerIdOption.Value!.Value);

            if (simpleListeningSession.JoinIdOption.IsSet)
                writer.WriteString("join_id", simpleListeningSession.JoinId);

            if (simpleListeningSession.QueuePlaylistIdOption.IsSet)
                writer.WriteString("queue_playlist_id", simpleListeningSession.QueuePlaylistId);

            if (simpleListeningSession.TitleOption.IsSet)
                writer.WriteString("title", simpleListeningSession.Title);

            if (simpleListeningSession.FallbackPlaylistIdOption.IsSet)
                writer.WriteString("fallback_playlist_id", simpleListeningSession.FallbackPlaylistId);

            if (simpleListeningSession.FallbackPlaylistShuffleOption.IsSet)
                writer.WriteBoolean("fallback_playlist_shuffle", simpleListeningSession.FallbackPlaylistShuffleOption.Value!.Value);
        }
    }
}
