// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SimpleUser
    /// </summary>
    public partial class SimpleUser : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SimpleUser" /> class.
        /// </summary>
        /// <param name="id">id</param>
        /// <param name="spotifyId">spotifyId</param>
        /// <param name="spotifyDisplayName">spotifyDisplayName</param>
        /// <param name="name">name</param>
        [JsonConstructor]
        public SimpleUser(Option<int?> id = default, Option<string?> spotifyId = default, Option<string?> spotifyDisplayName = default, Option<string?> name = default)
        {
            IdOption = id;
            SpotifyIdOption = spotifyId;
            SpotifyDisplayNameOption = spotifyDisplayName;
            NameOption = name;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Id
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> IdOption { get; private set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [JsonPropertyName("id")]
        public int? Id { get { return this.IdOption; } set { this.IdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyId
        /// </summary>
        [JsonPropertyName("spotify_id")]
        public string? SpotifyId { get { return this.SpotifyIdOption; } set { this.SpotifyIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyDisplayName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyDisplayNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyDisplayName
        /// </summary>
        [JsonPropertyName("spotify_display_name")]
        public string? SpotifyDisplayName { get { return this.SpotifyDisplayNameOption; } set { this.SpotifyDisplayNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of Name
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> NameOption { get; private set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [JsonPropertyName("name")]
        public string? Name { get { return this.NameOption; } set { this.NameOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SimpleUser {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  SpotifyId: ").Append(SpotifyId).Append("\n");
            sb.Append("  SpotifyDisplayName: ").Append(SpotifyDisplayName).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SimpleUser" />
    /// </summary>
    public class SimpleUserJsonConverter : JsonConverter<SimpleUser>
    {
        /// <summary>
        /// Deserializes json to <see cref="SimpleUser" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SimpleUser Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> id = default;
            Option<string?> spotifyId = default;
            Option<string?> spotifyDisplayName = default;
            Option<string?> name = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                id = new Option<int?>(utf8JsonReader.GetInt32());
                            break;
                        case "spotify_id":
                            spotifyId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "spotify_display_name":
                            spotifyDisplayName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "name":
                            name = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (id.IsSet && id.Value == null)
                throw new ArgumentNullException(nameof(id), "Property is not nullable for class SimpleUser.");

            if (spotifyId.IsSet && spotifyId.Value == null)
                throw new ArgumentNullException(nameof(spotifyId), "Property is not nullable for class SimpleUser.");

            if (spotifyDisplayName.IsSet && spotifyDisplayName.Value == null)
                throw new ArgumentNullException(nameof(spotifyDisplayName), "Property is not nullable for class SimpleUser.");

            if (name.IsSet && name.Value == null)
                throw new ArgumentNullException(nameof(name), "Property is not nullable for class SimpleUser.");

            return new SimpleUser(id, spotifyId, spotifyDisplayName, name);
        }

        /// <summary>
        /// Serializes a <see cref="SimpleUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="simpleUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SimpleUser simpleUser, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, simpleUser, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SimpleUser" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="simpleUser"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SimpleUser simpleUser, JsonSerializerOptions jsonSerializerOptions)
        {
            if (simpleUser.SpotifyIdOption.IsSet && simpleUser.SpotifyId == null)
                throw new ArgumentNullException(nameof(simpleUser.SpotifyId), "Property is required for class SimpleUser.");

            if (simpleUser.SpotifyDisplayNameOption.IsSet && simpleUser.SpotifyDisplayName == null)
                throw new ArgumentNullException(nameof(simpleUser.SpotifyDisplayName), "Property is required for class SimpleUser.");

            if (simpleUser.NameOption.IsSet && simpleUser.Name == null)
                throw new ArgumentNullException(nameof(simpleUser.Name), "Property is required for class SimpleUser.");

            if (simpleUser.IdOption.IsSet)
                writer.WriteNumber("id", simpleUser.IdOption.Value!.Value);

            if (simpleUser.SpotifyIdOption.IsSet)
                writer.WriteString("spotify_id", simpleUser.SpotifyId);

            if (simpleUser.SpotifyDisplayNameOption.IsSet)
                writer.WriteString("spotify_display_name", simpleUser.SpotifyDisplayName);

            if (simpleUser.NameOption.IsSet)
                writer.WriteString("name", simpleUser.Name);
        }
    }
}
