// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// SongRequest
    /// </summary>
    public partial class SongRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SongRequest" /> class.
        /// </summary>
        /// <param name="sessionId">sessionId</param>
        /// <param name="userId">userId</param>
        /// <param name="spotifyTrackId">spotifyTrackId</param>
        /// <param name="trackMetadata">trackMetadata</param>
        [JsonConstructor]
        public SongRequest(Option<long?> sessionId = default, Option<long?> userId = default, Option<string?> spotifyTrackId = default, Option<TrackMetaData?> trackMetadata = default)
        {
            SessionIdOption = sessionId;
            UserIdOption = userId;
            SpotifyTrackIdOption = spotifyTrackId;
            TrackMetadataOption = trackMetadata;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SessionId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> SessionIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SessionId
        /// </summary>
        [JsonPropertyName("session_id")]
        public long? SessionId { get { return this.SessionIdOption; } set { this.SessionIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of UserId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<long?> UserIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets UserId
        /// </summary>
        [JsonPropertyName("user_id")]
        public long? UserId { get { return this.UserIdOption; } set { this.UserIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of SpotifyTrackId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyTrackIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyTrackId
        /// </summary>
        [JsonPropertyName("spotify_track_id")]
        public string? SpotifyTrackId { get { return this.SpotifyTrackIdOption; } set { this.SpotifyTrackIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrackMetadata
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<TrackMetaData?> TrackMetadataOption { get; private set; }

        /// <summary>
        /// Gets or Sets TrackMetadata
        /// </summary>
        [JsonPropertyName("track_metadata")]
        public TrackMetaData? TrackMetadata { get { return this.TrackMetadataOption; } set { this.TrackMetadataOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SongRequest {\n");
            sb.Append("  SessionId: ").Append(SessionId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  SpotifyTrackId: ").Append(SpotifyTrackId).Append("\n");
            sb.Append("  TrackMetadata: ").Append(TrackMetadata).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="SongRequest" />
    /// </summary>
    public class SongRequestJsonConverter : JsonConverter<SongRequest>
    {
        /// <summary>
        /// Deserializes json to <see cref="SongRequest" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override SongRequest Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<long?> sessionId = default;
            Option<long?> userId = default;
            Option<string?> spotifyTrackId = default;
            Option<TrackMetaData?> trackMetadata = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "session_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                sessionId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "user_id":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                userId = new Option<long?>(utf8JsonReader.GetInt64());
                            break;
                        case "spotify_track_id":
                            spotifyTrackId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "track_metadata":
                            if (utf8JsonReader.TokenType != JsonTokenType.Null)
                                trackMetadata = new Option<TrackMetaData?>(JsonSerializer.Deserialize<TrackMetaData>(ref utf8JsonReader, jsonSerializerOptions)!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (sessionId.IsSet && sessionId.Value == null)
                throw new ArgumentNullException(nameof(sessionId), "Property is not nullable for class SongRequest.");

            if (userId.IsSet && userId.Value == null)
                throw new ArgumentNullException(nameof(userId), "Property is not nullable for class SongRequest.");

            if (spotifyTrackId.IsSet && spotifyTrackId.Value == null)
                throw new ArgumentNullException(nameof(spotifyTrackId), "Property is not nullable for class SongRequest.");

            if (trackMetadata.IsSet && trackMetadata.Value == null)
                throw new ArgumentNullException(nameof(trackMetadata), "Property is not nullable for class SongRequest.");

            return new SongRequest(sessionId, userId, spotifyTrackId, trackMetadata);
        }

        /// <summary>
        /// Serializes a <see cref="SongRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="songRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, SongRequest songRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, songRequest, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="SongRequest" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="songRequest"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, SongRequest songRequest, JsonSerializerOptions jsonSerializerOptions)
        {
            if (songRequest.SpotifyTrackIdOption.IsSet && songRequest.SpotifyTrackId == null)
                throw new ArgumentNullException(nameof(songRequest.SpotifyTrackId), "Property is required for class SongRequest.");

            if (songRequest.TrackMetadataOption.IsSet && songRequest.TrackMetadata == null)
                throw new ArgumentNullException(nameof(songRequest.TrackMetadata), "Property is required for class SongRequest.");

            if (songRequest.SessionIdOption.IsSet)
                writer.WriteNumber("session_id", songRequest.SessionIdOption.Value!.Value);

            if (songRequest.UserIdOption.IsSet)
                writer.WriteNumber("user_id", songRequest.UserIdOption.Value!.Value);

            if (songRequest.SpotifyTrackIdOption.IsSet)
                writer.WriteString("spotify_track_id", songRequest.SpotifyTrackId);

            if (songRequest.TrackMetadataOption.IsSet)
            {
                writer.WritePropertyName("track_metadata");
                JsonSerializer.Serialize(writer, songRequest.TrackMetadata, jsonSerializerOptions);
            }
        }
    }
}
