// <auto-generated>
/*
 * Spotifete Api
 *
 * Specfile for Spotifete
 *
 * The version of the OpenAPI document: 0.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// TrackMetaData
    /// </summary>
    public partial class TrackMetaData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackMetaData" /> class.
        /// </summary>
        /// <param name="spotifyTrackId">spotifyTrackId</param>
        /// <param name="trackName">trackName</param>
        /// <param name="artistName">artistName</param>
        /// <param name="albumName">albumName</param>
        /// <param name="albumImageThumbnailUrl">albumImageThumbnailUrl</param>
        [JsonConstructor]
        public TrackMetaData(Option<string?> spotifyTrackId = default, Option<string?> trackName = default, Option<string?> artistName = default, Option<string?> albumName = default, Option<string?> albumImageThumbnailUrl = default)
        {
            SpotifyTrackIdOption = spotifyTrackId;
            TrackNameOption = trackName;
            ArtistNameOption = artistName;
            AlbumNameOption = albumName;
            AlbumImageThumbnailUrlOption = albumImageThumbnailUrl;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of SpotifyTrackId
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> SpotifyTrackIdOption { get; private set; }

        /// <summary>
        /// Gets or Sets SpotifyTrackId
        /// </summary>
        [JsonPropertyName("spotify_track_id")]
        public string? SpotifyTrackId { get { return this.SpotifyTrackIdOption; } set { this.SpotifyTrackIdOption = new(value); } }

        /// <summary>
        /// Used to track the state of TrackName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> TrackNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets TrackName
        /// </summary>
        [JsonPropertyName("track_name")]
        public string? TrackName { get { return this.TrackNameOption; } set { this.TrackNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of ArtistName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> ArtistNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets ArtistName
        /// </summary>
        [JsonPropertyName("artist_name")]
        public string? ArtistName { get { return this.ArtistNameOption; } set { this.ArtistNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlbumName
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AlbumNameOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlbumName
        /// </summary>
        [JsonPropertyName("album_name")]
        public string? AlbumName { get { return this.AlbumNameOption; } set { this.AlbumNameOption = new(value); } }

        /// <summary>
        /// Used to track the state of AlbumImageThumbnailUrl
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> AlbumImageThumbnailUrlOption { get; private set; }

        /// <summary>
        /// Gets or Sets AlbumImageThumbnailUrl
        /// </summary>
        [JsonPropertyName("album_image_thumbnail_url")]
        public string? AlbumImageThumbnailUrl { get { return this.AlbumImageThumbnailUrlOption; } set { this.AlbumImageThumbnailUrlOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TrackMetaData {\n");
            sb.Append("  SpotifyTrackId: ").Append(SpotifyTrackId).Append("\n");
            sb.Append("  TrackName: ").Append(TrackName).Append("\n");
            sb.Append("  ArtistName: ").Append(ArtistName).Append("\n");
            sb.Append("  AlbumName: ").Append(AlbumName).Append("\n");
            sb.Append("  AlbumImageThumbnailUrl: ").Append(AlbumImageThumbnailUrl).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="TrackMetaData" />
    /// </summary>
    public class TrackMetaDataJsonConverter : JsonConverter<TrackMetaData>
    {
        /// <summary>
        /// Deserializes json to <see cref="TrackMetaData" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override TrackMetaData Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<string?> spotifyTrackId = default;
            Option<string?> trackName = default;
            Option<string?> artistName = default;
            Option<string?> albumName = default;
            Option<string?> albumImageThumbnailUrl = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "spotify_track_id":
                            spotifyTrackId = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "track_name":
                            trackName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "artist_name":
                            artistName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "album_name":
                            albumName = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "album_image_thumbnail_url":
                            albumImageThumbnailUrl = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        default:
                            break;
                    }
                }
            }

            if (spotifyTrackId.IsSet && spotifyTrackId.Value == null)
                throw new ArgumentNullException(nameof(spotifyTrackId), "Property is not nullable for class TrackMetaData.");

            if (trackName.IsSet && trackName.Value == null)
                throw new ArgumentNullException(nameof(trackName), "Property is not nullable for class TrackMetaData.");

            if (artistName.IsSet && artistName.Value == null)
                throw new ArgumentNullException(nameof(artistName), "Property is not nullable for class TrackMetaData.");

            if (albumName.IsSet && albumName.Value == null)
                throw new ArgumentNullException(nameof(albumName), "Property is not nullable for class TrackMetaData.");

            if (albumImageThumbnailUrl.IsSet && albumImageThumbnailUrl.Value == null)
                throw new ArgumentNullException(nameof(albumImageThumbnailUrl), "Property is not nullable for class TrackMetaData.");

            return new TrackMetaData(spotifyTrackId, trackName, artistName, albumName, albumImageThumbnailUrl);
        }

        /// <summary>
        /// Serializes a <see cref="TrackMetaData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackMetaData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, TrackMetaData trackMetaData, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, trackMetaData, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="TrackMetaData" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="trackMetaData"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, TrackMetaData trackMetaData, JsonSerializerOptions jsonSerializerOptions)
        {
            if (trackMetaData.SpotifyTrackIdOption.IsSet && trackMetaData.SpotifyTrackId == null)
                throw new ArgumentNullException(nameof(trackMetaData.SpotifyTrackId), "Property is required for class TrackMetaData.");

            if (trackMetaData.TrackNameOption.IsSet && trackMetaData.TrackName == null)
                throw new ArgumentNullException(nameof(trackMetaData.TrackName), "Property is required for class TrackMetaData.");

            if (trackMetaData.ArtistNameOption.IsSet && trackMetaData.ArtistName == null)
                throw new ArgumentNullException(nameof(trackMetaData.ArtistName), "Property is required for class TrackMetaData.");

            if (trackMetaData.AlbumNameOption.IsSet && trackMetaData.AlbumName == null)
                throw new ArgumentNullException(nameof(trackMetaData.AlbumName), "Property is required for class TrackMetaData.");

            if (trackMetaData.AlbumImageThumbnailUrlOption.IsSet && trackMetaData.AlbumImageThumbnailUrl == null)
                throw new ArgumentNullException(nameof(trackMetaData.AlbumImageThumbnailUrl), "Property is required for class TrackMetaData.");

            if (trackMetaData.SpotifyTrackIdOption.IsSet)
                writer.WriteString("spotify_track_id", trackMetaData.SpotifyTrackId);

            if (trackMetaData.TrackNameOption.IsSet)
                writer.WriteString("track_name", trackMetaData.TrackName);

            if (trackMetaData.ArtistNameOption.IsSet)
                writer.WriteString("artist_name", trackMetaData.ArtistName);

            if (trackMetaData.AlbumNameOption.IsSet)
                writer.WriteString("album_name", trackMetaData.AlbumName);

            if (trackMetaData.AlbumImageThumbnailUrlOption.IsSet)
                writer.WriteString("album_image_thumbnail_url", trackMetaData.AlbumImageThumbnailUrl);
        }
    }
}
